/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Gestion (void)
{
  GtkWidget *Gestion;
  GtkWidget *fixed2;
  GtkWidget *treeview;
  GtkWidget *label37;
  GtkWidget *button_ajouter;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label5;
  GtkWidget *label_affichage_meilleur_menu;
  GtkWidget *button_modifier;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label6;
  GtkWidget *button_supprimer;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label7;
  GtkWidget *button_rafraichir;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image28;
  GtkWidget *label43;
  GtkWidget *button_meilleur;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label8;

  Gestion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Gestion, 840, 550);
  gtk_window_set_title (GTK_WINDOW (Gestion), _("Gestion"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Gestion), fixed2);

  treeview = gtk_tree_view_new ();
  gtk_widget_show (treeview);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview, 24, 232);
  gtk_widget_set_size_request (treeview, 708, 240);

  label37 = gtk_label_new (_("---------------- Espace Nutritionniste ----------------\n"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed2), label37, 208, 24);
  gtk_widget_set_size_request (label37, 368, 56);

  button_ajouter = gtk_button_new ();
  gtk_widget_show (button_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), button_ajouter, 16, 112);
  gtk_widget_set_size_request (button_ajouter, 130, 30);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_ajouter), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox3), label5, FALSE, FALSE, 0);

  label_affichage_meilleur_menu = gtk_label_new (_("Le meilleur menu est = "));
  gtk_widget_show (label_affichage_meilleur_menu);
  gtk_fixed_put (GTK_FIXED (fixed2), label_affichage_meilleur_menu, 24, 176);
  gtk_widget_set_size_request (label_affichage_meilleur_menu, 752, 24);

  button_modifier = gtk_button_new ();
  gtk_widget_show (button_modifier);
  gtk_fixed_put (GTK_FIXED (fixed2), button_modifier, 168, 112);
  gtk_widget_set_size_request (button_modifier, 130, 30);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_modifier), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox4), label6, FALSE, FALSE, 0);

  button_supprimer = gtk_button_new ();
  gtk_widget_show (button_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), button_supprimer, 320, 112);
  gtk_widget_set_size_request (button_supprimer, 130, 30);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_supprimer), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-cut", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox5), label7, FALSE, FALSE, 0);

  button_rafraichir = gtk_button_new ();
  gtk_widget_show (button_rafraichir);
  gtk_fixed_put (GTK_FIXED (fixed2), button_rafraichir, 472, 112);
  gtk_widget_set_size_request (button_rafraichir, 130, 30);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button_rafraichir), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image28 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox17), image28, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("  Rafraichir"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox17), label43, FALSE, FALSE, 0);

  button_meilleur = gtk_button_new ();
  gtk_widget_show (button_meilleur);
  gtk_fixed_put (GTK_FIXED (fixed2), button_meilleur, 624, 112);
  gtk_widget_set_size_request (button_meilleur, 130, 30);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_meilleur), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-goto-top", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Meilleur menu"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox6), label8, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview, "row_activated",
                    G_CALLBACK (on_treeview_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter, "clicked",
                    G_CALLBACK (on_button_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier, "clicked",
                    G_CALLBACK (on_button_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer, "clicked",
                    G_CALLBACK (on_button_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_rafraichir, "clicked",
                    G_CALLBACK (on_button_rafraichir_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_meilleur, "clicked",
                    G_CALLBACK (on_button_meilleur_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion, Gestion, "Gestion");
  GLADE_HOOKUP_OBJECT (Gestion, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Gestion, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (Gestion, label37, "label37");
  GLADE_HOOKUP_OBJECT (Gestion, button_ajouter, "button_ajouter");
  GLADE_HOOKUP_OBJECT (Gestion, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Gestion, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Gestion, image3, "image3");
  GLADE_HOOKUP_OBJECT (Gestion, label5, "label5");
  GLADE_HOOKUP_OBJECT (Gestion, label_affichage_meilleur_menu, "label_affichage_meilleur_menu");
  GLADE_HOOKUP_OBJECT (Gestion, button_modifier, "button_modifier");
  GLADE_HOOKUP_OBJECT (Gestion, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Gestion, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Gestion, image4, "image4");
  GLADE_HOOKUP_OBJECT (Gestion, label6, "label6");
  GLADE_HOOKUP_OBJECT (Gestion, button_supprimer, "button_supprimer");
  GLADE_HOOKUP_OBJECT (Gestion, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Gestion, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Gestion, image5, "image5");
  GLADE_HOOKUP_OBJECT (Gestion, label7, "label7");
  GLADE_HOOKUP_OBJECT (Gestion, button_rafraichir, "button_rafraichir");
  GLADE_HOOKUP_OBJECT (Gestion, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Gestion, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Gestion, image28, "image28");
  GLADE_HOOKUP_OBJECT (Gestion, label43, "label43");
  GLADE_HOOKUP_OBJECT (Gestion, button_meilleur, "button_meilleur");
  GLADE_HOOKUP_OBJECT (Gestion, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Gestion, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Gestion, image6, "image6");
  GLADE_HOOKUP_OBJECT (Gestion, label8, "label8");

  return Gestion;
}

GtkWidget*
create_Rechercher (void)
{
  GtkWidget *Rechercher;
  GtkWidget *fixed3;
  GtkWidget *combobox_jour_rechercher;
  GtkWidget *label_jour_rechercher;
  GtkWidget *label_temps_rechercher;
  GtkWidget *label_rechercher;
  GtkWidget *button_home5;
  GtkWidget *image9;
  GtkWidget *button_chercher;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image25;
  GtkWidget *label38;
  GtkWidget *checkbutton_dejeuner_rechercher;
  GtkWidget *checkbutton_diner_rechercher;

  Rechercher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Rechercher, 555, 400);
  gtk_window_set_title (GTK_WINDOW (Rechercher), _("Rechercher"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Rechercher), fixed3);

  combobox_jour_rechercher = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_jour_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox_jour_rechercher, 245, 200);
  gtk_widget_set_size_request (combobox_jour_rechercher, 131, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_rechercher), _("lundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_rechercher), _("mardi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_rechercher), _("mercredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_rechercher), _("jeudi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_rechercher), _("vendredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_rechercher), _("samedi"));

  label_jour_rechercher = gtk_label_new (_("Jour De La Semaine :"));
  gtk_widget_show (label_jour_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed3), label_jour_rechercher, 40, 192);
  gtk_widget_set_size_request (label_jour_rechercher, 184, 40);

  label_temps_rechercher = gtk_label_new (_("Temps  :"));
  gtk_widget_show (label_temps_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed3), label_temps_rechercher, 96, 112);
  gtk_widget_set_size_request (label_temps_rechercher, 72, 32);

  label_rechercher = gtk_label_new (_("------ Espace Nutritionniste ------\n          ------ Recherche------"));
  gtk_widget_show (label_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed3), label_rechercher, 152, 16);
  gtk_widget_set_size_request (label_rechercher, 232, 64);

  button_home5 = gtk_button_new ();
  gtk_widget_show (button_home5);
  gtk_fixed_put (GTK_FIXED (fixed3), button_home5, 16, 16);
  gtk_widget_set_size_request (button_home5, 40, 32);

  image9 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_container_add (GTK_CONTAINER (button_home5), image9);

  button_chercher = gtk_button_new ();
  gtk_widget_show (button_chercher);
  gtk_fixed_put (GTK_FIXED (fixed3), button_chercher, 200, 288);
  gtk_widget_set_size_request (button_chercher, 136, 56);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_chercher), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image25 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox15), image25, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_(" chercher"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox15), label38, FALSE, FALSE, 0);

  checkbutton_dejeuner_rechercher = gtk_check_button_new_with_mnemonic (_("D\303\251jeuner"));
  gtk_widget_show (checkbutton_dejeuner_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton_dejeuner_rechercher, 280, 96);
  gtk_widget_set_size_request (checkbutton_dejeuner_rechercher, 120, 32);

  checkbutton_diner_rechercher = gtk_check_button_new_with_mnemonic (_("Diner"));
  gtk_widget_show (checkbutton_diner_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton_diner_rechercher, 280, 136);
  gtk_widget_set_size_request (checkbutton_diner_rechercher, 118, 32);

  g_signal_connect ((gpointer) button_home5, "clicked",
                    G_CALLBACK (on_button_home5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_chercher, "clicked",
                    G_CALLBACK (on_button_chercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_dejeuner_rechercher, "toggled",
                    G_CALLBACK (on_checkbutton_dejeuner_rechercher_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_diner_rechercher, "toggled",
                    G_CALLBACK (on_checkbutton_diner_rechercher_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Rechercher, Rechercher, "Rechercher");
  GLADE_HOOKUP_OBJECT (Rechercher, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Rechercher, combobox_jour_rechercher, "combobox_jour_rechercher");
  GLADE_HOOKUP_OBJECT (Rechercher, label_jour_rechercher, "label_jour_rechercher");
  GLADE_HOOKUP_OBJECT (Rechercher, label_temps_rechercher, "label_temps_rechercher");
  GLADE_HOOKUP_OBJECT (Rechercher, label_rechercher, "label_rechercher");
  GLADE_HOOKUP_OBJECT (Rechercher, button_home5, "button_home5");
  GLADE_HOOKUP_OBJECT (Rechercher, image9, "image9");
  GLADE_HOOKUP_OBJECT (Rechercher, button_chercher, "button_chercher");
  GLADE_HOOKUP_OBJECT (Rechercher, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Rechercher, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Rechercher, image25, "image25");
  GLADE_HOOKUP_OBJECT (Rechercher, label38, "label38");
  GLADE_HOOKUP_OBJECT (Rechercher, checkbutton_dejeuner_rechercher, "checkbutton_dejeuner_rechercher");
  GLADE_HOOKUP_OBJECT (Rechercher, checkbutton_diner_rechercher, "checkbutton_diner_rechercher");

  return Rechercher;
}

GtkWidget*
create_Ajout (void)
{
  GtkWidget *Ajout;
  GtkWidget *fixed4;
  GtkWidget *label_ajouter;
  GtkWidget *checkbutton_diner_ajouter;
  GtkWidget *button_home1;
  GtkWidget *image12;
  GtkWidget *button_enregister;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image14;
  GtkWidget *label15;
  GtkWidget *label_temps_ajouter;
  GtkWidget *checkbutton_dejeuner_ajouter;
  GtkWidget *table1;
  GtkWidget *label_jour1;
  GtkWidget *label_entree1;
  GtkWidget *label_plat_principal_1;
  GtkWidget *label_dessert1;
  GtkWidget *entry_entree_ajouter;
  GtkWidget *entry_plat_principal_ajouter;
  GtkWidget *entry_dessert_ajouter;
  GtkWidget *label_dechets1;
  GtkObject *spinbutton_dechets_ajouter_adj;
  GtkWidget *spinbutton_dechets_ajouter;
  GtkWidget *combobox_jour_ajouter;

  Ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Ajout, 600, 648);
  gtk_window_set_title (GTK_WINDOW (Ajout), _("Ajout"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Ajout), fixed4);

  label_ajouter = gtk_label_new (_("Espace Nutritionniste\n         ----- Ajouter -----"));
  gtk_widget_show (label_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed4), label_ajouter, 184, 8);
  gtk_widget_set_size_request (label_ajouter, 240, 64);

  checkbutton_diner_ajouter = gtk_check_button_new_with_mnemonic (_("Diner"));
  gtk_widget_show (checkbutton_diner_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton_diner_ajouter, 272, 144);
  gtk_widget_set_size_request (checkbutton_diner_ajouter, 118, 32);

  button_home1 = gtk_button_new ();
  gtk_widget_show (button_home1);
  gtk_fixed_put (GTK_FIXED (fixed4), button_home1, 32, 24);
  gtk_widget_set_size_request (button_home1, 48, 32);

  image12 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_container_add (GTK_CONTAINER (button_home1), image12);

  button_enregister = gtk_button_new ();
  gtk_widget_show (button_enregister);
  gtk_fixed_put (GTK_FIXED (fixed4), button_enregister, 224, 552);
  gtk_widget_set_size_request (button_enregister, 136, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_enregister), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image14 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox8), image14, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_(" Enregister"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox8), label15, FALSE, FALSE, 0);

  label_temps_ajouter = gtk_label_new (_("Temps  :"));
  gtk_widget_show (label_temps_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed4), label_temps_ajouter, 120, 120);
  gtk_widget_set_size_request (label_temps_ajouter, 72, 32);

  checkbutton_dejeuner_ajouter = gtk_check_button_new_with_mnemonic (_("D\303\251jeuner"));
  gtk_widget_show (checkbutton_dejeuner_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton_dejeuner_ajouter, 272, 112);
  gtk_widget_set_size_request (checkbutton_dejeuner_ajouter, 120, 32);

  table1 = gtk_table_new (5, 2, FALSE);
  gtk_widget_show (table1);
  gtk_fixed_put (GTK_FIXED (fixed4), table1, 80, 208);
  gtk_widget_set_size_request (table1, 426, 320);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 18);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 8);

  label_jour1 = gtk_label_new (_("Jour De La Semaine :"));
  gtk_widget_show (label_jour1);
  gtk_table_attach (GTK_TABLE (table1), label_jour1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_jour1, 184, 40);

  label_entree1 = gtk_label_new (_("Entree"));
  gtk_widget_show (label_entree1);
  gtk_table_attach (GTK_TABLE (table1), label_entree1, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_entree1, 184, 40);

  label_plat_principal_1 = gtk_label_new (_("Plat principal"));
  gtk_widget_show (label_plat_principal_1);
  gtk_table_attach (GTK_TABLE (table1), label_plat_principal_1, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_plat_principal_1, 184, 40);

  label_dessert1 = gtk_label_new (_("Dessert"));
  gtk_widget_show (label_dessert1);
  gtk_table_attach (GTK_TABLE (table1), label_dessert1, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_dessert1, 184, 40);

  entry_entree_ajouter = gtk_entry_new ();
  gtk_widget_show (entry_entree_ajouter);
  gtk_table_attach (GTK_TABLE (table1), entry_entree_ajouter, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_entree_ajouter), 8226);

  entry_plat_principal_ajouter = gtk_entry_new ();
  gtk_widget_show (entry_plat_principal_ajouter);
  gtk_table_attach (GTK_TABLE (table1), entry_plat_principal_ajouter, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_plat_principal_ajouter), 8226);

  entry_dessert_ajouter = gtk_entry_new ();
  gtk_widget_show (entry_dessert_ajouter);
  gtk_table_attach (GTK_TABLE (table1), entry_dessert_ajouter, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_dessert_ajouter), 8226);

  label_dechets1 = gtk_label_new (_("D\303\251chets en kg :"));
  gtk_widget_show (label_dechets1);
  gtk_table_attach (GTK_TABLE (table1), label_dechets1, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_dechets1, 144, 40);

  spinbutton_dechets_ajouter_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton_dechets_ajouter = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_dechets_ajouter_adj), 1, 0);
  gtk_widget_show (spinbutton_dechets_ajouter);
  gtk_table_attach (GTK_TABLE (table1), spinbutton_dechets_ajouter, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (spinbutton_dechets_ajouter, 60, 27);

  combobox_jour_ajouter = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_jour_ajouter);
  gtk_table_attach (GTK_TABLE (table1), combobox_jour_ajouter, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_ajouter), _("lundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_ajouter), _("mardi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_ajouter), _("mercredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_ajouter), _("jeudi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_ajouter), _("vendredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_ajouter), _("samedi"));

  g_signal_connect ((gpointer) checkbutton_diner_ajouter, "toggled",
                    G_CALLBACK (on_checkbutton_diner_ajouter_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_home1, "clicked",
                    G_CALLBACK (on_button_home1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_enregister, "clicked",
                    G_CALLBACK (on_button_enregister_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_dejeuner_ajouter, "toggled",
                    G_CALLBACK (on_checkbutton_dejeuner_ajouter_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout, Ajout, "Ajout");
  GLADE_HOOKUP_OBJECT (Ajout, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Ajout, label_ajouter, "label_ajouter");
  GLADE_HOOKUP_OBJECT (Ajout, checkbutton_diner_ajouter, "checkbutton_diner_ajouter");
  GLADE_HOOKUP_OBJECT (Ajout, button_home1, "button_home1");
  GLADE_HOOKUP_OBJECT (Ajout, image12, "image12");
  GLADE_HOOKUP_OBJECT (Ajout, button_enregister, "button_enregister");
  GLADE_HOOKUP_OBJECT (Ajout, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Ajout, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Ajout, image14, "image14");
  GLADE_HOOKUP_OBJECT (Ajout, label15, "label15");
  GLADE_HOOKUP_OBJECT (Ajout, label_temps_ajouter, "label_temps_ajouter");
  GLADE_HOOKUP_OBJECT (Ajout, checkbutton_dejeuner_ajouter, "checkbutton_dejeuner_ajouter");
  GLADE_HOOKUP_OBJECT (Ajout, table1, "table1");
  GLADE_HOOKUP_OBJECT (Ajout, label_jour1, "label_jour1");
  GLADE_HOOKUP_OBJECT (Ajout, label_entree1, "label_entree1");
  GLADE_HOOKUP_OBJECT (Ajout, label_plat_principal_1, "label_plat_principal_1");
  GLADE_HOOKUP_OBJECT (Ajout, label_dessert1, "label_dessert1");
  GLADE_HOOKUP_OBJECT (Ajout, entry_entree_ajouter, "entry_entree_ajouter");
  GLADE_HOOKUP_OBJECT (Ajout, entry_plat_principal_ajouter, "entry_plat_principal_ajouter");
  GLADE_HOOKUP_OBJECT (Ajout, entry_dessert_ajouter, "entry_dessert_ajouter");
  GLADE_HOOKUP_OBJECT (Ajout, label_dechets1, "label_dechets1");
  GLADE_HOOKUP_OBJECT (Ajout, spinbutton_dechets_ajouter, "spinbutton_dechets_ajouter");
  GLADE_HOOKUP_OBJECT (Ajout, combobox_jour_ajouter, "combobox_jour_ajouter");

  return Ajout;
}

GtkWidget*
create_Supprimer (void)
{
  GtkWidget *Supprimer;
  GtkWidget *fixed5;
  GtkWidget *label_suppresssion;
  GtkWidget *label_temps3;
  GtkWidget *label_jour3;
  GtkWidget *button_home3;
  GtkWidget *image17;
  GtkWidget *combobox_suppression;
  GtkWidget *button_suppression;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image15;
  GtkWidget *label19;
  GtkWidget *radiobutton_dejeuner3;
  GSList *radiobutton_dejeuner3_group = NULL;
  GtkWidget *radiobutton_diner3;

  Supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Supprimer, 555, 400);
  gtk_window_set_title (GTK_WINDOW (Supprimer), _("Supprimer"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Supprimer), fixed5);

  label_suppresssion = gtk_label_new (_("   Espace Nutritionniste\n      ---- Suppresssion ----"));
  gtk_widget_show (label_suppresssion);
  gtk_fixed_put (GTK_FIXED (fixed5), label_suppresssion, 176, 32);
  gtk_widget_set_size_request (label_suppresssion, 184, 56);

  label_temps3 = gtk_label_new (_("Temps:"));
  gtk_widget_show (label_temps3);
  gtk_fixed_put (GTK_FIXED (fixed5), label_temps3, 80, 144);
  gtk_widget_set_size_request (label_temps3, 73, 32);

  label_jour3 = gtk_label_new (_("Jour De la Semaine :"));
  gtk_widget_show (label_jour3);
  gtk_fixed_put (GTK_FIXED (fixed5), label_jour3, 72, 200);
  gtk_widget_set_size_request (label_jour3, 152, 48);

  button_home3 = gtk_button_new ();
  gtk_widget_show (button_home3);
  gtk_fixed_put (GTK_FIXED (fixed5), button_home3, 8, 8);
  gtk_widget_set_size_request (button_home3, 40, 32);

  image17 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_container_add (GTK_CONTAINER (button_home3), image17);

  combobox_suppression = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_suppression);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox_suppression, 264, 208);
  gtk_widget_set_size_request (combobox_suppression, 169, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_suppression), _("lundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_suppression), _("mardi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_suppression), _("mercredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_suppression), _("jeudi "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_suppression), _("vendredi "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_suppression), _("samedi"));

  button_suppression = gtk_button_new ();
  gtk_widget_show (button_suppression);
  gtk_fixed_put (GTK_FIXED (fixed5), button_suppression, 200, 312);
  gtk_widget_set_size_request (button_suppression, 128, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_suppression), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image15 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox9), image15, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_(" supprimer"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox9), label19, FALSE, FALSE, 0);

  radiobutton_dejeuner3 = gtk_radio_button_new_with_mnemonic (NULL, _("D\303\251jeuner"));
  gtk_widget_show (radiobutton_dejeuner3);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton_dejeuner3, 192, 144);
  gtk_widget_set_size_request (radiobutton_dejeuner3, 128, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_dejeuner3), radiobutton_dejeuner3_group);
  radiobutton_dejeuner3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_dejeuner3));

  radiobutton_diner3 = gtk_radio_button_new_with_mnemonic (NULL, _("Diner"));
  gtk_widget_show (radiobutton_diner3);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton_diner3, 320, 144);
  gtk_widget_set_size_request (radiobutton_diner3, 120, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_diner3), radiobutton_dejeuner3_group);
  radiobutton_dejeuner3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_diner3));

  g_signal_connect ((gpointer) button_home3, "clicked",
                    G_CALLBACK (on_button_home3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_suppression, "clicked",
                    G_CALLBACK (on_button_suppression_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_dejeuner3, "toggled",
                    G_CALLBACK (on_radiobutton_dejeuner3_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_diner3, "toggled",
                    G_CALLBACK (on_radiobutton_diner3_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Supprimer, Supprimer, "Supprimer");
  GLADE_HOOKUP_OBJECT (Supprimer, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Supprimer, label_suppresssion, "label_suppresssion");
  GLADE_HOOKUP_OBJECT (Supprimer, label_temps3, "label_temps3");
  GLADE_HOOKUP_OBJECT (Supprimer, label_jour3, "label_jour3");
  GLADE_HOOKUP_OBJECT (Supprimer, button_home3, "button_home3");
  GLADE_HOOKUP_OBJECT (Supprimer, image17, "image17");
  GLADE_HOOKUP_OBJECT (Supprimer, combobox_suppression, "combobox_suppression");
  GLADE_HOOKUP_OBJECT (Supprimer, button_suppression, "button_suppression");
  GLADE_HOOKUP_OBJECT (Supprimer, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Supprimer, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Supprimer, image15, "image15");
  GLADE_HOOKUP_OBJECT (Supprimer, label19, "label19");
  GLADE_HOOKUP_OBJECT (Supprimer, radiobutton_dejeuner3, "radiobutton_dejeuner3");
  GLADE_HOOKUP_OBJECT (Supprimer, radiobutton_diner3, "radiobutton_diner3");

  return Supprimer;
}

GtkWidget*
create_authentification (void)
{
  GtkWidget *authentification;
  GtkWidget *fixed6;
  GtkWidget *entry_login;
  GtkWidget *entry_id;
  GtkWidget *label39;
  GtkWidget *label_id;
  GtkWidget *label_login;
  GtkWidget *button_connection;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image18;
  GtkWidget *label22;

  authentification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (authentification, 555, 400);
  gtk_window_set_title (GTK_WINDOW (authentification), _("authentification"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (authentification), fixed6);

  entry_login = gtk_entry_new ();
  gtk_widget_show (entry_login);
  gtk_fixed_put (GTK_FIXED (fixed6), entry_login, 264, 120);
  gtk_widget_set_size_request (entry_login, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_login), 8226);

  entry_id = gtk_entry_new ();
  gtk_widget_show (entry_id);
  gtk_fixed_put (GTK_FIXED (fixed6), entry_id, 264, 176);
  gtk_widget_set_size_request (entry_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id), 8226);

  label39 = gtk_label_new (_("------- Authentification -------"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed6), label39, 176, 32);
  gtk_widget_set_size_request (label39, 192, 32);

  label_id = gtk_label_new (_("Votre Identifiant  :"));
  gtk_widget_show (label_id);
  gtk_fixed_put (GTK_FIXED (fixed6), label_id, 64, 176);
  gtk_widget_set_size_request (label_id, 136, 32);

  label_login = gtk_label_new (_("Login  :"));
  gtk_widget_show (label_login);
  gtk_fixed_put (GTK_FIXED (fixed6), label_login, 72, 112);
  gtk_widget_set_size_request (label_login, 112, 32);

  button_connection = gtk_button_new ();
  gtk_widget_show (button_connection);
  gtk_fixed_put (GTK_FIXED (fixed6), button_connection, 200, 288);
  gtk_widget_set_size_request (button_connection, 128, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_connection), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image18 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox10), image18, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_(" Connection"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox10), label22, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_connection, "clicked",
                    G_CALLBACK (on_button_connection_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (authentification, authentification, "authentification");
  GLADE_HOOKUP_OBJECT (authentification, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (authentification, entry_login, "entry_login");
  GLADE_HOOKUP_OBJECT (authentification, entry_id, "entry_id");
  GLADE_HOOKUP_OBJECT (authentification, label39, "label39");
  GLADE_HOOKUP_OBJECT (authentification, label_id, "label_id");
  GLADE_HOOKUP_OBJECT (authentification, label_login, "label_login");
  GLADE_HOOKUP_OBJECT (authentification, button_connection, "button_connection");
  GLADE_HOOKUP_OBJECT (authentification, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (authentification, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (authentification, image18, "image18");
  GLADE_HOOKUP_OBJECT (authentification, label22, "label22");

  return authentification;
}

GtkWidget*
create_Modifier (void)
{
  GtkWidget *Modifier;
  GtkWidget *fixed9;
  GtkWidget *label_temps_modification;
  GtkWidget *checkbutton_diner_modification;
  GtkWidget *label9modifier;
  GtkWidget *table2;
  GtkWidget *label_jour_modification;
  GtkWidget *label_entree_modification;
  GtkWidget *label_plat_principal;
  GtkWidget *label_dessert;
  GtkWidget *entry_modification;
  GtkWidget *entry_plat_modification;
  GtkWidget *entry_dessert_modification;
  GtkWidget *label_dechets;
  GtkObject *spinbutton_dechets_modification_adj;
  GtkWidget *spinbutton_dechets_modification;
  GtkWidget *combobox_jour_modification;
  GtkWidget *checkbutton_dejeuner_modification;
  GtkWidget *button_sauvegarder;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image26;
  GtkWidget *label42;
  GtkWidget *button_home2;
  GtkWidget *image27;

  Modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Modifier, 600, 648);
  gtk_window_set_title (GTK_WINDOW (Modifier), _("Modifier"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (Modifier), fixed9);

  label_temps_modification = gtk_label_new (_("Temps  :"));
  gtk_widget_show (label_temps_modification);
  gtk_fixed_put (GTK_FIXED (fixed9), label_temps_modification, 120, 120);
  gtk_widget_set_size_request (label_temps_modification, 72, 32);

  checkbutton_diner_modification = gtk_check_button_new_with_mnemonic (_("Diner"));
  gtk_widget_show (checkbutton_diner_modification);
  gtk_fixed_put (GTK_FIXED (fixed9), checkbutton_diner_modification, 272, 144);
  gtk_widget_set_size_request (checkbutton_diner_modification, 118, 32);

  label9modifier = gtk_label_new (_("------ Espace Nutritionniste ------\n          ------ Modification ------"));
  gtk_widget_show (label9modifier);
  gtk_fixed_put (GTK_FIXED (fixed9), label9modifier, 184, 8);
  gtk_widget_set_size_request (label9modifier, 240, 64);

  table2 = gtk_table_new (5, 2, FALSE);
  gtk_widget_show (table2);
  gtk_fixed_put (GTK_FIXED (fixed9), table2, 80, 208);
  gtk_widget_set_size_request (table2, 426, 320);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 18);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 8);

  label_jour_modification = gtk_label_new (_("Jour De La Semaine :"));
  gtk_widget_show (label_jour_modification);
  gtk_table_attach (GTK_TABLE (table2), label_jour_modification, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_jour_modification, 184, 40);

  label_entree_modification = gtk_label_new (_("Entree"));
  gtk_widget_show (label_entree_modification);
  gtk_table_attach (GTK_TABLE (table2), label_entree_modification, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_entree_modification, 184, 40);

  label_plat_principal = gtk_label_new (_("Plat principal"));
  gtk_widget_show (label_plat_principal);
  gtk_table_attach (GTK_TABLE (table2), label_plat_principal, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_plat_principal, 184, 40);

  label_dessert = gtk_label_new (_("Dessert"));
  gtk_widget_show (label_dessert);
  gtk_table_attach (GTK_TABLE (table2), label_dessert, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_dessert, 184, 40);

  entry_modification = gtk_entry_new ();
  gtk_widget_show (entry_modification);
  gtk_table_attach (GTK_TABLE (table2), entry_modification, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_modification), 8226);

  entry_plat_modification = gtk_entry_new ();
  gtk_widget_show (entry_plat_modification);
  gtk_table_attach (GTK_TABLE (table2), entry_plat_modification, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_plat_modification), 8226);

  entry_dessert_modification = gtk_entry_new ();
  gtk_widget_show (entry_dessert_modification);
  gtk_table_attach (GTK_TABLE (table2), entry_dessert_modification, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_dessert_modification), 8226);

  label_dechets = gtk_label_new (_("D\303\251chets en kg :"));
  gtk_widget_show (label_dechets);
  gtk_table_attach (GTK_TABLE (table2), label_dechets, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label_dechets, 144, 40);

  spinbutton_dechets_modification_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton_dechets_modification = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_dechets_modification_adj), 1, 0);
  gtk_widget_show (spinbutton_dechets_modification);
  gtk_table_attach (GTK_TABLE (table2), spinbutton_dechets_modification, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (spinbutton_dechets_modification, 60, 27);

  combobox_jour_modification = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_jour_modification);
  gtk_table_attach (GTK_TABLE (table2), combobox_jour_modification, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_modification), _("lundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_modification), _("mardi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_modification), _("mercredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_modification), _("jeudi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_modification), _("vendredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_jour_modification), _("samedi"));

  checkbutton_dejeuner_modification = gtk_check_button_new_with_mnemonic (_("D\303\251jeuner"));
  gtk_widget_show (checkbutton_dejeuner_modification);
  gtk_fixed_put (GTK_FIXED (fixed9), checkbutton_dejeuner_modification, 272, 112);
  gtk_widget_set_size_request (checkbutton_dejeuner_modification, 120, 32);

  button_sauvegarder = gtk_button_new ();
  gtk_widget_show (button_sauvegarder);
  gtk_fixed_put (GTK_FIXED (fixed9), button_sauvegarder, 224, 552);
  gtk_widget_set_size_request (button_sauvegarder, 136, 48);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button_sauvegarder), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image26 = gtk_image_new_from_stock ("gtk-floppy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox16), image26, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_(" Sauvegarder"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox16), label42, FALSE, FALSE, 0);

  button_home2 = gtk_button_new ();
  gtk_widget_show (button_home2);
  gtk_fixed_put (GTK_FIXED (fixed9), button_home2, 32, 24);
  gtk_widget_set_size_request (button_home2, 48, 32);

  image27 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_container_add (GTK_CONTAINER (button_home2), image27);

  g_signal_connect ((gpointer) checkbutton_diner_modification, "toggled",
                    G_CALLBACK (on_checkbutton_diner_modification_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_dejeuner_modification, "toggled",
                    G_CALLBACK (on_checkbutton_dejeuner_modification_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_home2, "clicked",
                    G_CALLBACK (on_button_home2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modifier, Modifier, "Modifier");
  GLADE_HOOKUP_OBJECT (Modifier, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (Modifier, label_temps_modification, "label_temps_modification");
  GLADE_HOOKUP_OBJECT (Modifier, checkbutton_diner_modification, "checkbutton_diner_modification");
  GLADE_HOOKUP_OBJECT (Modifier, label9modifier, "label9modifier");
  GLADE_HOOKUP_OBJECT (Modifier, table2, "table2");
  GLADE_HOOKUP_OBJECT (Modifier, label_jour_modification, "label_jour_modification");
  GLADE_HOOKUP_OBJECT (Modifier, label_entree_modification, "label_entree_modification");
  GLADE_HOOKUP_OBJECT (Modifier, label_plat_principal, "label_plat_principal");
  GLADE_HOOKUP_OBJECT (Modifier, label_dessert, "label_dessert");
  GLADE_HOOKUP_OBJECT (Modifier, entry_modification, "entry_modification");
  GLADE_HOOKUP_OBJECT (Modifier, entry_plat_modification, "entry_plat_modification");
  GLADE_HOOKUP_OBJECT (Modifier, entry_dessert_modification, "entry_dessert_modification");
  GLADE_HOOKUP_OBJECT (Modifier, label_dechets, "label_dechets");
  GLADE_HOOKUP_OBJECT (Modifier, spinbutton_dechets_modification, "spinbutton_dechets_modification");
  GLADE_HOOKUP_OBJECT (Modifier, combobox_jour_modification, "combobox_jour_modification");
  GLADE_HOOKUP_OBJECT (Modifier, checkbutton_dejeuner_modification, "checkbutton_dejeuner_modification");
  GLADE_HOOKUP_OBJECT (Modifier, button_sauvegarder, "button_sauvegarder");
  GLADE_HOOKUP_OBJECT (Modifier, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Modifier, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Modifier, image26, "image26");
  GLADE_HOOKUP_OBJECT (Modifier, label42, "label42");
  GLADE_HOOKUP_OBJECT (Modifier, button_home2, "button_home2");
  GLADE_HOOKUP_OBJECT (Modifier, image27, "image27");

  return Modifier;
}

