/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Gestion (void);
GtkWidget* create_Rechercher (void);
GtkWidget* create_Ajout (void);
GtkWidget* create_Supprimer (void);
GtkWidget* create_authentification (void);
GtkWidget* create_Modifier (void);
