/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Gestion;
  GtkWidget *Rechercher;
  GtkWidget *Ajout;
  GtkWidget *Supprimer;
  GtkWidget *authentification;
  GtkWidget *Modifier;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  //Gestion = create_Gestion ();
  //gtk_widget_show (Gestion);
  //Rechercher = create_Rechercher ();
  //gtk_widget_show (Rechercher);
  //Ajout = create_Ajout ();
  //gtk_widget_show (Ajout);
  //Supprimer = create_Supprimer ();
  //gtk_widget_show (Supprimer);
  authentification = create_authentification ();
  gtk_widget_show (authentification);
  //Modifier = create_Modifier ();
  //gtk_widget_show (Modifier);

  gtk_main ();
  return 0;
}

